DROP TABLE CP4_USER CASCADE CONSTRAINTS;

DROP SEQUENCE CP4_USER_SEQ;

DROP TABLE CP4_TASK CASCADE CONSTRAINTS;

DROP SEQUENCE CP4_TASK_SEQ;

DROP TABLE CP4_STATUS CASCADE CONSTRAINTS;

DROP SEQUENCE CP4_STATUS_SEQ;
